export const productArray = [
  {
    name: "Ping Pong",
    description: "Sports Game",
    image: "images/GameHub_covers.jpg",
    id: "1",
    price: 59.99,
  },
  {
    name: "SuperDuper",
    description: "Heroes Game",
    image: "images/GameHub_covers2.jpg",
    id: "2",
    price: 59.99,
  },
  {
    name: "Black",
    description: "Heroes Game",
    image: "images/GameHub_covers3.jpg",
    id: "3",
    price: 59.99,
  },
  {
    name: "Furious",
    description: "Heroes Game",
    image: "images/GameHub_covers4.jpg",
    id: "4",
    price: 59.99,
  },
  {
    name: "Assassin",
    description: "Adventure/Action",
    image: "images/GameHub_covers5.jpg",
    id: "5",
    price: 59.99,
  },
  {
    name: "Space Wars",
    description: "Action/Sci-Fi",
    image: "images/GameHub_covers6.jpg",
    id: "6",
    price: 59.99,
  },
  {
    name: "Racing",
    description: "Motorsport",
    image: "images/GameHub_covers7.jpg",
    id: "7",
    price: 59.99,
  },
  {
    name: "Boxer",
    description: "Sports",
    image: "images/GameHub_covers8.jpg",
    id: "8",
    price: 59.99,
  },
  {
    name: "CyberPunk",
    description: "Sci-fi",
    image: "images/GameHub_covers9.jpg",
    id: "9",
    price: 59.99,
  },
  {
    name: "Forge Legends",
    description: "Adventure/RPG",
    image: "images/GameHub_covers10.jpg",
    id: "10",
    price: 59.99,
  },
];
